# Generated by Django 5.2.4 on 2025-08-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_contact_alter_new_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(upload_to='news_images'),
        ),
    ]
