# Generated by Django 5.2.4 on 2025-08-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_new_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='view_count',
        ),
    ]
