# Generated by Django 5.2.4 on 2025-08-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_remove_new_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
