# Generated by Django 5.2.4 on 2025-08-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_new_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
