# Generated by Django 5.2.4 on 2025-08-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0009_alter_new_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
