# Generated by Django 5.2.4 on 2025-08-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0010_alter_new_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='view_count',
        ),
    ]
